services:
  eureka-server:
    image: eureka-server:latest
    ports:
      - "8761:8761"
    environment:
      PORT: 8761
    restart: "no"

  api-gateway:
    image: api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    restart: "no"

  paciente-service:
    image: paciente-service:latest
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 8081
      DB_URL: jdbc:mysql://host.docker.internal:3306/paciente_db
      DB_USERNAME: root
      DB_PASSWORD: ""
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 2
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 0
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 300000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 60000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    depends_on:
      - eureka-server
    restart: "no"

  medico-service:
    image: medico-service:latest
    ports:
      - "8082:8082"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 8082
      DB_URL: jdbc:mysql://host.docker.internal:3306/medico_db
      DB_USERNAME: root
      DB_PASSWORD: ""
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 2
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 0
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 300000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 60000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    depends_on:
      - eureka-server
    restart: "no"

  atencion-service:
    image: atencion-service:latest
    ports:
      - "8083:8083"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 8083
      DB_URL: jdbc:mysql://host.docker.internal:3306/atencion_db
      DB_USERNAME: root
      DB_PASSWORD: ""
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 2
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 0
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 300000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 60000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    depends_on:
      - eureka-server
      - paciente-service
      - medico-service
    restart: "no"

  diagnostico-service:
    image: diagnostico-service:latest
    ports:
      - "8084:8084"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 8084
      DB_URL: jdbc:mysql://host.docker.internal:3306/diagnostico_db
      DB_USERNAME: root
      DB_PASSWORD: ""
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 2
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 0
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 300000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 60000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    depends_on:
      - eureka-server
      - atencion-service
    restart: "no"

  receta-service:
    image: receta-service:latest
    ports:
      - "8085:8085"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 8085
      DB_URL: jdbc:mysql://host.docker.internal:3306/receta_db
      DB_USERNAME: root
      DB_PASSWORD: ""
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 2
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 0
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 300000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 60000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    depends_on:
      - eureka-server
      - diagnostico-service
    restart: "no"

  medicamento-service:
    image: medicamento-service:latest
    ports:
      - "8086:8086"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 8086
      DB_URL: jdbc:mysql://host.docker.internal:3306/medicamento_db
      DB_USERNAME: root
      DB_PASSWORD: ""
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 2
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 0
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 300000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 60000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    depends_on:
      - eureka-server
    restart: "no"

  examen-service:
    image: examen-service:latest
    ports:
      - "8087:8087"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 8087
      DB_URL: jdbc:mysql://host.docker.internal:3306/examen_db
      DB_USERNAME: root
      DB_PASSWORD: ""
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 2
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 0
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 300000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 60000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    depends_on:
      - eureka-server
      - atencion-service
    restart: "no"

  agenda-service:
    image: agenda-service:latest
    ports:
      - "8088:8088"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 8088
      DB_URL: jdbc:mysql://host.docker.internal:3306/agenda_db
      DB_USERNAME: root
      DB_PASSWORD: ""
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 3
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 0
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 300000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 60000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    depends_on:
      - eureka-server
      - paciente-service
      - medico-service
    restart: "no"

  usuario-service:
    image: usuario-service:latest
    ports:
      - "8089:8089"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 8089
      DB_URL: jdbc:mysql://host.docker.internal:3306/usuario_db
      DB_USERNAME: root
      DB_PASSWORD: ""
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 2
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 0
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 300000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 60000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    depends_on:
      - eureka-server
    restart: "no"

  centro-medico-service:
    image: centro-medico-service:latest
    ports:
      - "8090:8090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 8090
      DB_URL: jdbc:mysql://host.docker.internal:3306/centro_medico_db
      DB_USERNAME: root
      DB_PASSWORD: ""
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 2
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 0
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 300000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 60000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    depends_on:
      - eureka-server
    restart: "no"